version: '3.1'
networks:
  network-pro:
    external:
      name: o-net
services:
    zookeeper-1:
        image: zookeeper
        hostname: zookeeper-1
        networks:
            - network-pro
        ports:
            - 2181:2181
        deploy:
            resources:
              limits:
                cpus: '0.5'
                memory: 2048M
            update_config:
                parallelism: 1
                delay: 1s
            restart_policy:
                condition: on-failure
                delay: 1s
                max_attempts: 3
            placement:
                constraints:
                - Engine.Labels.label_name == dubbo
        environment:
            ZOO_MY_ID: 1
            ZOO_TICK_TIME: 4000
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

    zookeeper-2:
        image: zookeeper
        hostname: zookeeper-2
        networks:
            - network-pro
        ports:
            - 2182:2181
        deploy:
            resources:
              limits:
                cpus: '0.5'
                memory: 2048M
            update_config:
                parallelism: 1
                delay: 1s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                - Engine.Labels.label_name == wx
        environment:
            ZOO_MY_ID: 2
            ZOO_TICK_TIME: 4000
            ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper-3:2888:3888

    zookeeper-3:
        image: zookeeper
        hostname: zookeeper-3
        networks:
            - network-pro
        deploy:
            resources:
              limits:
                cpus: '0.5'
                memory: 2048M
            update_config:
                parallelism: 1
                delay: 1s
            restart_policy:
                condition: on-failure
                delay: 1s
                max_attempts: 3
            placement:
                constraints:
                - Engine.Labels.label_name == wx
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_TICK_TIME: 4000
            ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=0.0.0.0:2888:3888
