FROM       docker.io/openshift/base-centos7
MAINTAINER linux
ADD 1.8.0_144.tar.gz  /usr/local
ENV JAVA_HOME /usr/local/1.8.0_144
ENV JRE_HOME /usr/local/1.8.0_144/jre
ENV CLASSPATH .:$JAVA_HOME/jre/lib/rt.jar  :$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $JAVA_HOME/bin:$PATH

ENV TIME_ZONE Asia/Shanghai
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV CATALINA_HOME /usr/local/tomcat
#ENV JAVA_OPTS="-server -Xmx1024m -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8"
ENV JAVA_OPTS="-Djava.awt.headless=true -Dfile.encoding=UTF-8 \
-server -Xms1024m -Xmx1024m \
-XX:NewSize=512m -XX:MaxNewSize=512m -XX:PermSize=512m \
-XX:MaxPermSize=512m -XX:+DisableExplicitGC"
WORKDIR  /usr/local/tomcat
ENV APP_DIR ${CATALINA_HOME}/webapps/
COPY ./apache-tomcat-8.5.2.tar.gz /usr/src
#ADD entrypoint.sh /
#COPY *.war ${APP_DIR}
RUN set -x \
    \
    && tar zxf /usr/src/apache-tomcat-8.5.2.tar.gz -C /usr/local \
    && rm -rf /usr/src/apache-tomcat-8.5.2.tar.gz \
    && echo "${TIME_ZONE}" > /etc/timezone \
    && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime
#    && yum install unzip -y
#    && chmod +x /entrypoint.sh \
#    && unzip -q ${APP_DIR}/*.war -d /usr/local/tomcat/webapps/ROOT/

EXPOSE 8080
